CREATE SCHEMA IF NOT EXISTS db1;

DROP TABLE IF EXISTS db1.table1;

CREATE TABLE db1.table1 (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  int1 INT NOT NULL,
  float2 FLOAT NOT NULL,
  string3 VARCHAR(250) DEFAULT NULL,
  date4 DATE DEFAULT NULL
);